version: "{build}"

# GitHub specific alternative to `clone_depth: <number>`
shallow_clone: true

clone_folder: c:\gopath\src\github.com\philippgille\serve

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  # Install tools
  - choco install upx

build_script:
  - go build
  - ps: .\build.ps1 -isAppVeyor

test_script:
  - .\serve.exe -v
  - .\serve.exe -t
  # Use PowerShell for glob. ".\" is necessary in this case.
  - ps: .\artifacts\serve_v*_Windows_x64.exe -v

artifacts:
- path: artifacts\*
