git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - sudo apt-get install -y upx-ucl

script:
  - go build
  - build/build.sh
  # test
  - ./serve -v
  - ./serve -t
  - build/artifacts/serve_v*_Linux_x64 -v
  - build/artifacts/serve_v*_Linux_x64 -t
